spring:
  main:
    banner-mode: OFF

server:
  port: 7080
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true

GCS_BUCKET: klagevedlegg