apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: klage-file-api
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  image: {{ image }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  port: 7080
  accessPolicy:
    inbound:
      rules:
        - application: klage-arkiver-journalpost
        - application: klage-dittnav-api
  startup:
    path: /internal/health
    initialDelay: 10
    timeout: 3
    periodSeconds: 5
    failureThreshold: 10
  liveness:
    path: /internal/health
    timeout: 3
    periodSeconds: 2
    failureThreshold: 3
  readiness:
    path: /internal/health
    timeout: 3
    periodSeconds: 2
    failureThreshold: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  webproxy: true
  gcp:
    buckets:
    {{#each buckets}}
       - name: {{this}}
    {{/each}}
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
  {{#each envs}}
     - name: {{name}}
       value: {{value}}
  {{/each}}